title: Anju Maurya # your name (or website title) here
logo: "https://ibb.co/mvr43Gd" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  College Junior, Aspiring Data Analyst
  <br><br>
  Machine Learning, Software Development
  <br><br>
  <a href="https://www.linkedin.com/in/anju-maurya-19008a230/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
